# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "swift"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      time: "02:00"
    reviewers:
      - sethonyango
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      time: "02:00"
    reviewers:
      - mburumaxwell
  - package-ecosystem: "devcontainers"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      time: "02:00"
    reviewers:
      - mburumaxwell
