name: Build PR

on:
  pull_request:
    branches: [ main ]
    paths-ignore: # do not trigger for changes:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - docs/**

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Resolve dependencies
      run: swift package resolve
      continue-on-error: true
    - name: Run tests
      run: swift test -v
      ## setting continue-on-error: true will cause failure
      ## because 'swift test' writes content to stderr
      #continue-on-error: true
