name: Fix Whitespaces

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:
  fix:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Fix whitespaces
      uses: andreasabel/fix-whitespace-action@v1
      with:
        fix: true
        verbose: true

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Fix whitespaces
        title: Fix whitespaces
        branch: fix-whitespaces
